### PR TITLE
Compute AV1 mime using colorimetry info

### PR DESCRIPTION
**Pull request by rafaelcaricio**
Use available colorimetry information to completely calculate the codec string for AV1 streams.

### CODE REVIEW

**Comment by rafaelcaricio** [comment]
Example manifest after this change:
```
#EXTM3U
#EXT-X-VERSION:7
#EXT-X-INDEPENDENT-SEGMENTS
#EXT-X-MEDIA:TYPE=AUDIO,URI="audio_0/manifest.m3u8",GROUP-ID="audio",LANGUAGE="en",NAME="audio_0",DEFAULT=YES,AUTOSELECT=YES,CHANNELS="2"
#EXT-X-STREAM-INF:BANDWIDTH=1024000,CODECS="av01.0.31M.08.0.110.06.06.06.0",RESOLUTION=256x144,AUDIO="audio"
av1_0/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1024000,CODECS="hev1",RESOLUTION=640x360,AUDIO="audio"
h265_0/manifest.m3u8
#EXT-X-STREAM-INF:BANDWIDTH=1024000,CODECS="avc1.4D401E",RESOLUTION=640x360,AUDIO="audio"
h264_0/manifest.m3u8
```

**Comment by flavioribeiro** [comment]
@rafaelcaricio could you confirm this codec string is supported on browsers?

**Comment by rafaelcaricio** [comment]
I don't have Safari 17.0 with one of the recently released Apple devices with AV1 hardware decoder to test. 🥲 But it plays AV1 with hls.js in Chrome and Firefox. The WebKit blog post points to the spec with this codec string https://webkit.org/blog/14445/webkit-features-in-safari-17-0/#AV1 I would assume that it should play as well.

**Comment by flavioribeiro** [comment]
@robwalch any thoughts on this?

**Comment by flavioribeiro** [comment]
refs https://github.com/video-dev/hls.js/pull/5774

**Comment by rafaelcaricio** [comment]
This code should actually be present in GStreamer. I plan to send a patch upstream to have it done there, which would remove the need to do those calculations here.

**Pull request merged**
